### ISSUE TITLE
Limite de consultas excedido (QUOTA_EXCEEDED)

### ISSUE THREAD

**Issue by giovanigenerali** [casadosdados/sinesp-consulta-placa#1]
@jhonata-menezes eles estão limitando, eu ainda não tinha visto esse retorno deles. abri essa issue apenas para deixar registrado.

```
{
  "codigoRetorno": "1",
  "mensagemRetorno": "Limite de consultas excedido. Tente novamente mais tarde."
}
```

**Comment by jhonata-menezes** [comment]
> @jhonata-menezes eles estão limitando, eu ainda não tinha visto esse retorno deles. abri essa issue apenas para deixar registrado.
> 
> ```
> {
>   "codigoRetorno": "1",
>   "mensagemRetorno": "Limite de consultas excedido. Tente novamente mais tarde."
> }
> ```

@giovanigenerali troquei o método de geração do token, voltei a usar um fork da lib, teoricamente não deverá ocorrer mais esse problema por estar gerando device id diferente. Mas irei deixar essa issue aberta por mais 2 dias, caso não ocorra nada relacionado novamente estarei fechando.

Obrigado.

**Comment by vbeal** [comment]
{
codigoRetorno: "1",
mensagemRetorno: "Limite de consultas excedido. Tente novamente mais tarde.",
}

**Comment by jhonata-menezes** [comment]
> {
> codigoRetorno: "1",
> mensagemRetorno: "Limite de consultas excedido. Tente novamente mais tarde.",
> }

Correção realizada, Sinesp tinha começado a validar alguns campos internamente.

Estou fechando a issue pois foi feito a correção. Caso volte por favor abrir uma nova issue.

**Comment by megabites** [comment]
Boa tarde @jhonata-menezes, cara primeiro parabéns pela api ta me ajudando muito. 

estou tentando fazer algumas pesquisas em um loop e não consigo fazer está retornando o mesmo erro reportado 

{
codigoRetorno: "1",
mensagemRetorno: "Limite de consultas excedido. Tente novamente mais tarde.",
}
