### ISSUE TITLE
PHONE_REGISTRATION_ERROR

### ISSUE THREAD

**Issue by arivanbastos** [casadosdados/sinesp-consulta-placa#3]
Estou rodando a API no Node 10.16.1, mas logo após iniciar o server obtenho sucessivas vezes o erro Register request has failed with Error=PHONE_REGISTRATION_ERROR.

**Comment by jhonata-menezes** [comment]
Voce esta em uma rede residencial? quando executo em um ambiente local demora a obter um token, quando executa no ambiente de produção (Digital Ocean) é bem rápido. Pode demorar a obter um token, mas em algum momento deve obter, no máximo uns 60 segundos.

**Comment by arivanbastos** [comment]
Verdade, esperei mais alguns instantes e inicio. Também consegui consultar as placas!
