### ISSUE TITLE
Limite de consultas excedido. Tente novamente mais tarde

### ISSUE THREAD

**Issue by megabites** [casadosdados/sinesp-consulta-placa#4]
Boa tarde @jhonata-menezes, cara primeiro parabéns pela api ta me ajudando muito.

estou tentando fazer algumas pesquisas em um loop e não consigo fazer está retornando o mesmo erro reportado

{
codigoRetorno: "1",
mensagemRetorno: "Limite de consultas excedido. Tente novamente mais tarde.",
}

**Comment by jhonata-menezes** [comment]
@megabites esse erro acontece devido ao limite de requisições por IP, quando acontecer isso tem que trocar o IP que faz a solicitação.

**Comment by Jorge-Nunes** [comment]
Boa noite @jhonata-menezes, Poderia dar um help, executei com docker, porem esta apresentando esta mensagem ao realizar a consulta: 

{"status":"error","message":"TypeError: Cannot read property 'replace' of undefined"},

Rapaz estou iniciando e ficaria muito grato se pudesse ajudar.  Estou chamando assim http://meuhost:3000/sinesp/placa/XYZ5564 Tks!

**Comment by samuelterra22** [comment]
@Jorge-Nunes seu problema pode ser parecido com o que eu reportei na Issue https://github.com/casadosdados/sinesp-consulta-placa/issues/5 ...
