### ISSUE TITLE
Register request has failed with Error=PHONE_REGISTRATION_ERROR

### ISSUE THREAD

**Issue by samuelterra22** [casadosdados/sinesp-consulta-placa#5]
Estou obtendo essa mensagem quando faço clone do projeto em minha máquina. Pesquisei em todo do código se poderia ser algo mais simples com o token e suspeito que o problema seja na push-receiver. Olhei o código da lib e notei que [nessa linha](https://github.com/casadosdados/push-receiver/blob/master/src/gcm/index.js#L10) já era pra ter tratado esse problema.

![image](https://user-images.githubusercontent.com/11915449/79711441-2bd45200-829e-11ea-9a1a-7f5609690fb4.png)

Como consequência, sai estourando try-catch onde faz split e replaces no token.

![image](https://user-images.githubusercontent.com/11915449/79711663-d0569400-829e-11ea-8bc6-6ed9c6b6f191.png)

O estranho que fiz o teste com Docker e funcionou normal... não se pode ser pelo ambiente ou da imagem gerada com um código diferente.

Alguém com o mesmo problema ou que passou e conseguiu consertar?

**Comment by AdilsonJR6** [comment]
Estou com o mesmo problema, quando rodo no Mac executa perfeitamente, no ubuntu nas maquinas de produção não registra.
