### ISSUE TITLE
Falha na instalação

### ISSUE THREAD

**Issue by Renato-Sanchez** [casadosdados/sinesp-consulta-placa#6]
boa tarde  @jhonata-menezes, desde a semana passada tenho recebido a msg abaixo nas consultas ao sinesp. Sera que alteraram algo ?

{"codigoRetorno":"8","mensagemRetorno":"Instalação inválida. Tente novamente ou re-instale o aplicativo."}

Obrigado

**Comment by jhonata-menezes** [comment]
@Renato-Sanchez provavelmente atualizaram o aplicativo. Tem que atualizar a chave
