### ISSUE TITLE
Versão Desatualizada?

### ISSUE THREAD

**Issue by luiscastelli** [casadosdados/sinesp-consulta-placa#7]
{"codigoRetorno":"7","mensagemRetorno":"Versão desatualizada. Favor atualizar aplicativo."}

Tem algo que eu possa fazer para auxiliar na correção?

**Comment by matheusodilon** [comment]
Também com o mesmo problema aqui

**Comment by AdilsonIndalencio** [comment]
Também com o mesmo problema

**Comment by gamadoleo** [comment]
Alguem consegiu algo?

**Comment by gamadoleo** [comment]
Alguem conseguiu capturar o request de consulta? tentei aqui mas sem sucesso.

**Comment by jhonata-menezes** [comment]
Provavelmente atualizaram a chave de acesso, se alguem conseguir a nova faz PR

https://github.com/casadosdados/sinesp-consulta-placa/blob/master/src/app/sinesp.js#L8

**Comment by gamadoleo** [comment]
Tentei utilizar o Charles, mas na captura não obtive os dados do header.

**Comment by jhonata-menezes** [comment]
@gamadoleo da ultima vez que tentei pegar a chave tinha que ser obtida debugando o app, a chave esta compilada em uma lib escrita em `c`

**Comment by gamadoleo** [comment]
ixe... e qual o procedimento para conseguir extrair essa chave? você não teria como tentar realizar o procedimento novamente?

**Comment by jhonata-menezes** [comment]
Mudaram o endpoint e o formato da API, eu não vou conseguir mudar rapido, mas caso queiram o curl que o app faz, esta na mão

```bash
curl -H 'accept: application/json' -H 'geolocation: -45.833647,-24.7437281' -H 'geolocationtimestamp: 2020-05-14T14:03:40.985Z' -H 'geolocationaccuracy: 14' -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; XT1097 Build/MPES24.49-18-7; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/75.0.3770.101 Mobile Safari/537.36' -H 'adsid: 00038dbf-8fa7-4383-aae4-2587b994b1ee' -H 'Host: cidadao2.sinesp.gov.br' --compressed 'https://cidadao2.sinesp.gov.br/api/vehicles/GGG5600'
```

**Comment by gamadoleo** [comment]
> Mudaram o endpoint e o formato da API, eu não vou conseguir mudar rapido, mas caso queiram o curl que o app faz, esta na mão
> 
> ```shell
> curl -H 'accept: application/json' -H 'geolocation: -45.833647,-24.7437281' -H 'geolocationtimestamp: 2020-05-14T14:03:40.985Z' -H 'geolocationaccuracy: 14' -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; XT1097 Build/MPES24.49-18-7; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/75.0.3770.101 Mobile Safari/537.36' -H 'adsid: 00038dbf-8fa7-4383-aae4-2587b994b1ee' -H 'Host: cidadao2.sinesp.gov.br' --compressed 'https://cidadao2.sinesp.gov.br/api/vehicles/GGG5600'
> ```

valeu, vou verificar, utilizou qual aplicativo para capturar o request?

**Comment by jhonata-menezes** [comment]
> > Mudaram o endpoint e o formato da API, eu não vou conseguir mudar rapido, mas caso queiram o curl que o app faz, esta na mão
> > ```shell
> > curl -H 'accept: application/json' -H 'geolocation: -45.833647,-24.7437281' -H 'geolocationtimestamp: 2020-05-14T14:03:40.985Z' -H 'geolocationaccuracy: 14' -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; XT1097 Build/MPES24.49-18-7; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/75.0.3770.101 Mobile Safari/537.36' -H 'adsid: 00038dbf-8fa7-4383-aae4-2587b994b1ee' -H 'Host: cidadao2.sinesp.gov.br' --compressed 'https://cidadao2.sinesp.gov.br/api/vehicles/GGG5600'
> > ```
> 
> valeu, vou verificar, utilizou qual aplicativo para capturar o request?

charles proxy - https://www.charlesproxy.com/

**Comment by gamadoleo** [comment]
ok, estou realizando alguns testes aqui... com os dados do curl que você passou é apenas a execução do get a url, e os dados são retornando... bem simples, porem estou com dúvida quanto a esse parametro
"adsid" se podemos ter limitações com esse número?

**Comment by gamadoleo** [comment]
deixaram muito mais simples... pois está consultando sem precisar daquelas friscuras do google... porem existe um limite de consultas...

**Comment by gamadoleo** [comment]
> > > Mudaram o endpoint e o formato da API, eu não vou conseguir mudar rapido, mas caso queiram o curl que o app faz, esta na mão
> > > ```shell
> > > curl -H 'accept: application/json' -H 'geolocation: -45.833647,-24.7437281' -H 'geolocationtimestamp: 2020-05-14T14:03:40.985Z' -H 'geolocationaccuracy: 14' -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; XT1097 Build/MPES24.49-18-7; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/75.0.3770.101 Mobile Safari/537.36' -H 'adsid: 00038dbf-8fa7-4383-aae4-2587b994b1ee' -H 'Host: cidadao2.sinesp.gov.br' --compressed 'https://cidadao2.sinesp.gov.br/api/vehicles/GGG5600'
> > > ```
> > 
> > 
> > valeu, vou verificar, utilizou qual aplicativo para capturar o request?
> 
> charles proxy - https://www.charlesproxy.com/

não entendi porque eu não havia conseguido capturar o curl, eu fiz assim instalei ele no windows e configurei o proxy no wifi do meu android e a captura não mostrou como a sua.

**Comment by luiscastelli** [comment]
> Mudaram o endpoint e o formato da API, eu não vou conseguir mudar rapido, mas caso queiram o curl que o app faz, esta na mão
> 
> ```shell
> curl -H 'accept: application/json' -H 'geolocation: -45.833647,-24.7437281' -H 'geolocationtimestamp: 2020-05-14T14:03:40.985Z' -H 'geolocationaccuracy: 14' -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; XT1097 Build/MPES24.49-18-7; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/75.0.3770.101 Mobile Safari/537.36' -H 'adsid: 00038dbf-8fa7-4383-aae4-2587b994b1ee' -H 'Host: cidadao2.sinesp.gov.br' --compressed 'https://cidadao2.sinesp.gov.br/api/vehicles/GGG5600'
> ```

Muito Obrigado por enquanto meu caro. Alterei meu sistema para usar esse cmd pelo curl e esta funcionando ok.
Quando terminar a alteração e o projeto aqui voltar a funcionar normal pode fechar esse issue. Abraço o/

**Comment by felipeescher** [comment]
> > Mudaram o endpoint e o formato da API, eu não vou conseguir mudar rapido, mas caso queiram o curl que o app faz, esta na mão
> > ```shell
> > curl -H 'accept: application/json' -H 'geolocation: -45.833647,-24.7437281' -H 'geolocationtimestamp: 2020-05-14T14:03:40.985Z' -H 'geolocationaccuracy: 14' -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; XT1097 Build/MPES24.49-18-7; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/75.0.3770.101 Mobile Safari/537.36' -H 'adsid: 00038dbf-8fa7-4383-aae4-2587b994b1ee' -H 'Host: cidadao2.sinesp.gov.br' --compressed 'https://cidadao2.sinesp.gov.br/api/vehicles/GGG5600'
> > ```
> 
> Muito Obrigado por enquanto meu caro. Alterei meu sistema para usar esse cmd pelo curl e esta funcionando ok.
> Quando terminar a alteração e o projeto aqui voltar a funcionar normal pode fechar esse issue. Abraço o/

Esse curl estava funcionando até sexta comigo, porém agora está retornando 403, mais alguém também aconteceu isso?

**Comment by gamadoleo** [comment]
modifique **oadsid** que volta a funcionar... porem vi que eles agora limitaram as consultas a uma consulta por minuto, provavelmente porque alguém está executando muitas consultas.

**Comment by jhonata-menezes** [comment]
Pessoal, como não to conseguindo encontrar tempo para manter o projeto atualizado vou arquivar o mesmo.
Abraços.
